# Generated by Django 4.0.3 on 2022-04-02 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=2)),
                ('ref', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Notei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=2)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('ref', models.CharField(max_length=5)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='todo.note')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PONote',
            fields=[
                ('notei_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todo.notei')),
                ('typ', models.CharField(default='PO', max_length=2)),
            ],
            bases=('todo.notei',),
        ),
        migrations.CreateModel(
            name='PSNote',
            fields=[
                ('notei_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todo.notei')),
                ('typ', models.CharField(default='PS', max_length=2)),
            ],
            bases=('todo.notei',),
        ),
        migrations.CreateModel(
            name='NoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField()),
                ('qty', models.PositiveSmallIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='todo.product')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('is_done', models.BooleanField(default=False)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masters', to='todo.master')),
            ],
        ),
        migrations.CreateModel(
            name='PSNoteItem',
            fields=[
                ('noteitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todo.noteitem')),
                ('typ', models.CharField(default='PS', max_length=2)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psnotes', to='todo.psnote')),
            ],
            bases=('todo.noteitem',),
        ),
        migrations.CreateModel(
            name='PONoteItem',
            fields=[
                ('noteitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todo.noteitem')),
                ('typ', models.CharField(default='PO', max_length=2)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ponotes', to='todo.ponote')),
            ],
            bases=('todo.noteitem',),
        ),
    ]
