# Generated by Django 4.0.3 on 2022-03-22 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_noteitem_is_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='notetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notetypes', to='note.notetype'),
        ),
    ]
