# Generated by Django 4.0.3 on 2022-03-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_alter_note_notetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
    ]
