# Generated by Django 4.0.3 on 2022-03-22 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0005_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='note.status'),
        ),
    ]
