# Generated by Django 4.0.3 on 2022-03-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0006_note_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteitem',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default='2022-03-21 17:59:26.071088'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noteitem',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='noteitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
