# Generated by Django 4.0.3 on 2022-03-26 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0008_so_soitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='noteitem',
            name='notetypekey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='note.notetype'),
            preserve_default=False,
        ),
    ]
