# Generated by Django 4.0.3 on 2022-03-28 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0009_noteitem_notetypekey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='notetype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='note.notetype'),
        ),
        migrations.AlterField(
            model_name='noteitem',
            name='notetypekey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notetypes', to='note.notetype'),
        ),
    ]
